- name: variable
  hosts: localhost
  vars:
   COURSE: devops
   TRAINER: shasi
   DURATION: 110
  tasks:
  - name: printing
    ansible.builtin.debug:
      msg: "helli, i am learning {{COURSE}}, trainer is {{TRAINER}} and duration {{DURATION}}"
 



