- name: varaible
  hosts: localhost
  vars:
  - name: USERNAME
    promt: please enter your username
    private: false
  - name: PASSWORD
    promt:
    private: true
  tasks:
  - name: print values
    ansible.builtin.debug:
     msg: "username: {{USERNAME}}, password:{{PASSWORD}}"

    


